language: python
python:
  - "3.4"

# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
  - "cd cohpy"
  - "python manage.py runserver"
  - sleep 3 # give Web server some time to bind to sockets, etc

# command to run tests
script:
  - "py.test -v"
