language: python
python:
  - "3.4"

# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
  - psql -c "create database cohpy;" -U postgres
  - "cd cohpy"
  - "python manage.py migrate" 
  - "python manage.py loaddata testdata.json" 
  - "nohup python manage.py runserver &"

# command to run tests
script:
  - "py.test -v"
